apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: run-simple-dotnet-pipeline-
spec:
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        metadata:
          name: pipeline-workspace
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
  pipelineRef:
    name: simple-dotnet-pipeline  
  params:
    - name: git-url
      value: https://github.com/vccampbell/s2i-dotnetcore-ex
    - name: git-branch
      value: dotnetcore-3.1-openshift-manual-pipeline
    - name: deployment-name
      value: deployment-name
  resources:
    - name: source-repository
      resourceRef:
        name: simple-dotnet-project-source
