---
apiVersion: v1
kind: Secret
metadata:
  name: docker-io
  namespace: cicd
  annotations:
    tekton.dev/docker-0: https://docker.io  
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJqYXlqd2FnbmVyIiwicGFzc3dvcmQiOiJkY2tyX3BhdF9pQVRQMnVqMk1sZk5WV0ZEMDczSmsxSzBPY3ciLCJlbWFpbCI6ImpheS53YWduZXJAY29tcG9yaXVtLmNvbSIsImF1dGgiOiJhbUY1YW5kaFoyNWxjanBrWTJ0eVgzQmhkRjlwUVZSUU1uVnFNazFzWms1V1YwWkVNRGN6U21zeFN6QlBZM2M9In19fQ==
